# Generated by Django 4.2.4 on 2023-08-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='insight',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
    ]
