# Generated by Django 4.2.4 on 2023-08-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image_its'),
        ('insight', '0002_insight_created_by_insight_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_cover', to='base.image', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='insights', to='base.tag'),
        ),
    ]
