# Generated by Django 4.2.6 on 2023-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_author_serie_serieitem_topic_remove_insight_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='notify_newsletter',
            field=models.BooleanField(default=True, verbose_name='notify newsletter'),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='linkedin'),
        ),
    ]
