# Generated by Django 4.2.6 on 2023-10-19 09:51

from django.db import migrations, models
import django.db.models.functions.text
import uhtred.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_alter_serie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=None, error_messages={'unique': 'An author with that username already exists'}, max_length=25, null=True, unique=True, validators=[uhtred.core.validators.UsernameValidator(), uhtred.core.validators.NoPoitSequenceValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_author_username'),
        ),
    ]
