# Generated by Django 4.2.4 on 2023-08-15 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, verbose_name='slug')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('buy_at', models.URLField(verbose_name='buy at')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cover', to='base.image', verbose_name='cover')),
                ('tags', models.ManyToManyField(related_name='products', to='base.tag')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_product_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_product_slug'),
        ),
    ]
