# Generated by Django 4.2.4 on 2023-08-14 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, verbose_name='slug')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('buy_at', models.URLField(blank=True, default='', verbose_name='buy at')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cover', to='base.image', verbose_name='cover')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
