# Generated by Django 4.2.4 on 2023-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_at',
            field=models.URLField(verbose_name='buy at'),
        ),
    ]
