# Generated by Django 4.2.6 on 2023-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_insight_notify_newsletter_alter_author_linkedin'),
        ('base', '0002_image_its'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='see_prices',
            field=models.BooleanField(default=False, verbose_name='see prices'),
        ),
        migrations.AddField(
            model_name='product',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='products', to='insight.topic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.tag'),
        ),
    ]
