# Generated by Django 4.2.6 on 2023-11-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_see_prices_product_topics_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pt_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='(pt) name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='price'),
        ),
    ]
