# Generated by Django 4.2.4 on 2023-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_person'),
        ('store', '0003_product_unique_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='base.tag'),
        ),
    ]
