# Generated by Django 4.2.4 on 2023-08-15 21:35

from django.db import migrations, models
import django.db.models.deletion
import martor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('pt_title', models.CharField(max_length=200, verbose_name='pt title')),
                ('description', models.CharField(blank=True, default=str, max_length=240, verbose_name='description')),
                ('pt_description', models.CharField(blank=True, default=str, max_length=240, verbose_name='pt description')),
                ('content', martor.models.MartorField(blank=True, default=str, verbose_name='content')),
                ('pt_content', martor.models.MartorField(blank=True, default=str, verbose_name='content')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='additional data')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('banner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_banner', to='base.image', verbose_name='banner')),
                ('banner_dark', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_banner_dark', to='base.image', verbose_name='banner dark')),
                ('brand_logo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_brand_logo', to='base.image', verbose_name='brand logo')),
                ('brand_logo_dark', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_brand_logo_dark', to='base.image', verbose_name='brand logo dark')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_cover', to='base.image', verbose_name='cover')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_case_title'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_case_slug'),
        ),
    ]
