# Generated by Django 4.2.4 on 2023-08-08 20:52

from django.db import migrations, models
import django.db.models.deletion
import martor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('pt_title', models.CharField(max_length=200, verbose_name='pt title')),
                ('description', models.CharField(blank=True, default=str, max_length=240, verbose_name='description')),
                ('pt_description', models.CharField(blank=True, default=str, max_length=240, verbose_name='pt description')),
                ('content', martor.models.MartorField(verbose_name='content')),
                ('pt_content', martor.models.MartorField(verbose_name='pt content')),
                ('banner_dark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_banner_dark', to='base.image', verbose_name='banner dark')),
                ('banner_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_banner_light', to='base.image', verbose_name='banner light')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_cover', to='base.image', verbose_name='cover')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
    ]
