# Generated by Django 4.2.4 on 2023-08-09 11:46

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content',
            field=martor.models.MartorField(blank=True, default=str, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pt_content',
            field=martor.models.MartorField(blank=True, default=str, verbose_name='content'),
        ),
    ]
