# Generated by Django 4.2.4 on 2023-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_case_content_alter_case_pt_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
