# Generated by Django 4.2.4 on 2023-08-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('case', '0003_case_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='brand_logo_dark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_brand_logo_dark', to='base.image', verbose_name='brand_logo dark'),
        ),
        migrations.AddField(
            model_name='case',
            name='brand_logo_light',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_brand_logo_light', to='base.image', verbose_name='brand_logo light'),
        ),
    ]
