# Generated by Django 4.2.4 on 2023-08-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('case', '0004_case_brand_logo_dark_case_brand_logo_light'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='banner_light',
        ),
        migrations.RemoveField(
            model_name='case',
            name='brand_logo_light',
        ),
        migrations.AddField(
            model_name='case',
            name='banner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_banner', to='base.image', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='case',
            name='brand_logo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_brand_logo', to='base.image', verbose_name='brand logo'),
        ),
        migrations.AlterField(
            model_name='case',
            name='banner_dark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_banner_dark', to='base.image', verbose_name='banner dark'),
        ),
        migrations.AlterField(
            model_name='case',
            name='brand_logo_dark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_brand_logo_dark', to='base.image', verbose_name='brand logo dark'),
        ),
    ]
