# Generated by Django 4.2.4 on 2023-08-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_file'),
        ('case', '0005_remove_case_banner_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='banner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_banner', to='base.image', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='banner_dark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_banner_dark', to='base.image', verbose_name='banner dark'),
        ),
        migrations.AlterField(
            model_name='case',
            name='brand_logo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_brand_logo', to='base.image', verbose_name='brand logo'),
        ),
        migrations.AlterField(
            model_name='case',
            name='brand_logo_dark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_brand_logo_dark', to='base.image', verbose_name='brand logo dark'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_cover', to='base.image', verbose_name='cover'),
        ),
    ]
