# Generated by Django 4.2.4 on 2023-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_alter_case_banner_alter_case_banner_dark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, verbose_name='slug'),
        ),
    ]
