# Generated by Django 4.2.4 on 2023-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_alter_case_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='data',
            field=models.JSONField(default=dict, verbose_name='additional data'),
        ),
    ]
