# Generated by Django 4.2.4 on 2023-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_case_banner_alter_case_banner_dark_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_case_title'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_case_slug'),
        ),
    ]
