# Generated by Django 4.2.6 on 2023-10-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese')], default=None, max_length=2, null=True, verbose_name='preferred language'),
        ),
    ]
