# Generated by Django 4.2.4 on 2023-08-08 20:45

from django.db import migrations, models
import uhtred.base.models.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(blank=True, default='', help_text='describe what image is for', max_length=250, verbose_name='name')),
                ('file', models.ImageField(upload_to=uhtred.base.models.image.images_upload_to)),
                ('thumbnail', models.ImageField(default=None, editable=False, null=True, upload_to=uhtred.base.models.image.images_upload_to, verbose_name='image thumbnail')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
