# Generated by Django 4.2.4 on 2023-08-15 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uhtred.base.models.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(blank=True, default='', help_text='describe what image is for', max_length=250, verbose_name='name')),
                ('file', models.ImageField(upload_to=uhtred.base.models.image.images_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'gif', 'jpg', 'jpeg'])])),
                ('thumbnail', models.ImageField(default=None, editable=False, null=True, upload_to=uhtred.base.models.image.images_upload_to, verbose_name='image thumbnail')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('headline', models.CharField(max_length=100, verbose_name='headline')),
                ('job_title', models.CharField(max_length=100, verbose_name='job title')),
                ('company_name', models.CharField(blank=True, default=str, max_length=100, verbose_name='company name')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'person',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('text', models.TextField(verbose_name='text')),
                ('pt_text', models.TextField(blank=True, default=str, verbose_name='text (PT)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=200, verbose_name='slug')),
                ('pt_name', models.CharField(blank=True, default='', max_length=60, verbose_name='name (PT)')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_tag_slug'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='base.person'),
        ),
        migrations.AddField(
            model_name='quote',
            name='brand_logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_brand_logo', to='base.image', verbose_name='brand logo'),
        ),
        migrations.AddField(
            model_name='quote',
            name='brand_logo_dark',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_brand_logo_dark', to='base.image', verbose_name='brand logo dark'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image', verbose_name='avatar'),
        ),
    ]
