# Generated by Django 4.2.4 on 2023-08-09 12:31

import django.core.validators
from django.db import migrations, models
import uhtred.base.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=uhtred.base.models.image.images_upload_to, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'gif', 'jpg', 'jpeg'])]),
        ),
    ]
