# Generated by Django 4.2.4 on 2023-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='its',
            field=models.CharField(blank=True, choices=[('case_cover', 'case cover'), ('case_banner', 'case banner'), ('brand_logo', 'brand logo'), ('avatar', 'user avatar'), ('insight_content', 'insight content'), ('insight_cover', 'insight cover')], default=None, max_length=16, null=True, verbose_name="it's"),
        ),
    ]
