# Generated by Django 4.2.4 on 2023-08-13 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tag_slug_tag_unique_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('headline', models.CharField(max_length=100, verbose_name='headline')),
                ('job_title', models.CharField(max_length=100, verbose_name='job title')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('avatar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image', verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'person',
            },
        ),
    ]
