# Generated by Django 4.2.4 on 2023-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, default=str, max_length=100, verbose_name='company name'),
        ),
    ]
