# Generated by Django 4.2.4 on 2023-08-24 14:33

from django.db import migrations, models
import uhtred.core.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_image_its'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id')),
                ('name', models.CharField(blank=True, default=str, max_length=60, validators=[uhtred.core.validators.NameValidator(), uhtred.core.validators.NoPoitSequenceValidator()], verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('verified', models.BooleanField(default=False, verbose_name='verifeid')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('tags', models.ManyToManyField(blank=True, related_name='emails_list', to='base.tag')),
            ],
            options={
                'verbose_name': 'email list',
                'verbose_name_plural': 'emails list',
            },
        ),
        migrations.AddConstraint(
            model_name='emaillist',
            constraint=models.UniqueConstraint(condition=models.Q(('verified', True)), fields=('email', 'verified'), name='unique_verified_email'),
        ),
    ]
