# Generated by Django 4.2.4 on 2023-08-25 11:36

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emaillist',
            name='unique_verified_email',
        ),
        migrations.AddConstraint(
            model_name='emaillist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email'),
        ),
    ]
